### ISSUE TITLE
vcs: Move out into a dedicated repo, reconsider API to play better with sourcegraph/go-vcs.

### ISSUE THREAD

**Issue by shurcooL** [shurcooL/go#18]
The [`github.com/shurcooL/go/vcs`](https://godoc.org/github.com/shurcooL/go/vcs) package has enough value that there may be external users of it, and its API/functionality may benefit from optimization to integrate better with the [`sourcegraph.com/sourcegraph/go-vcs/vcs`](https://godoc.org/sourcegraph.com/sourcegraph/go-vcs/vcs) Go package.

Consider moving it out into a separate repo and/or integrate or change it as needed to improve the overall Go package situation (improve interoperability, reduce overlap).

This package is heavily used at the core of `gostatus`, `Go-Package-Store` and `Conception-go`, but I can update those easily if needed.

**Comment by renstrom** [comment]
Somewhat related, would you consider this for `github_flavored_markdown` as well? I wanted to use it for a project, but vendoring it pulls in `github.com/shurcooL/go` together with *all* its dependencies, which are huge.

**Comment by shurcooL** [comment]
Sure, I can factor `github_flavored_markdown` out into a standalone repo. Can you make it a separate issue please?

But vendoring it should only vendor the package and its dependencies, not everything in the repo. I guess the vendoring implementation is more basic.

**Comment by shurcooL** [comment]
This is mostly done now:

https://godoc.org/github.com/shurcooL/vcsstate

All that's left to resolve this is to stop using the old package in a [few more places](https://godoc.org/github.com/shurcooL/go/vcs?importers), and remove it.

**Comment by shurcooL** [comment]
The old package is no longer used anywhere important after the changes above, so it can now be safely removed.

![image](https://cloud.githubusercontent.com/assets/1924134/13914513/0c1eab92-ef0c-11e5-9b7c-8bd5d769a6bf.png)

(`github.com/shurcooL/play/...` are temporary learning packages that are not maintained, that's why it's okay to break them.)
