### ISSUE TITLE
github flavored markdown to support task lists

### ISSUE THREAD

**Issue by damtur** [shurcooL/go#22]
Currently github_flavored_markdown is not supporting tasks list
(https://github.com/blog/1375%0A-task-lists-in-gfm-issues-pulls-comments)
Can you please add that functionality?

**Comment by shurcooL** [comment]
Hi @damtur,

This is a valid issue, however, the GitHub Flavored Markdown package has moved out into a standalone repository:

https://github.com/shurcooL/github_flavored_markdown

Could you please move this issue there (by closing this one and opening an identical one over there)? Thanks!

**Comment by damtur** [comment]
Done
Thanks
