### ISSUE TITLE
generated: ParseFile does not handle \r\n line endings.

### ISSUE THREAD

**Issue by monicaq** [shurcooL/go#30]
One fix is to replace use of bufio.Reader with bufio.Scanner.

**Comment by shurcooL** [comment]
Thanks for reporting.

When can /r/n line endings occur? Will a `gofmt`ed file on Windows have /n or /n/r line endings?

Using bufio.Scanner is not an option because it will fail on files that contains lines longer than 64k.

**Comment by monicaq** [comment]
The \r\n line ending can occur at any time.  

The gofmt program works the same on Windows as on other platforms.  The gofmt program removes \r from the source.

**Comment by shurcooL** [comment]
I see, so `gofmt`ed code will never contain /r/n line endings. Thanks for information.

> The \r\n line ending can occur at any time.

You mean if an editor you're using saves with /r/n line endings, and you don't run `gofmt` on it afterwards, right?

**Comment by monicaq** [comment]
Yes, if an editor uses \r\n and you don't gofmt it.   

The specification considers \r as whitespace and not part of the line terminator. The gofmt command removes \r as part of its normalization of the whitespace in the source.

Although the specification does not consider \r to be part of the line terminator, some editors do.  You should snip of the \r for those of us who are not fortunate to use a *nix type system.

**Comment by shurcooL** [comment]
This has been resolved in 5a468291046daeb2d6155b9e3f47af601af298ed.

Thanks again for reporting the bug.
