### ISSUE TITLE
Open URLs with $BROWSER if set

### ISSUE THREAD

**Issue by mvdan** [shurcooL/go#32]
This would be very useful to me on Linux.

I have both Chromium and Chrome installed, and they tend to fight each other to become the default browser in the XDG settings. Frustratingly enough, this time I can't seem to get Chromium to win. Thus, `xdg-open some-url` opens Chrome and I can't seem to fix it.

After reading https://wiki.archlinux.org/index.php/default_applications, I also want to give up all hope of configuring this properly.

Luckily, there's a standard of setting the `BROWSER` environment variable, which almost all terminal applications follow. Could you make the `open` package follow it if the `path` is an HTTP(s) URL and the var is set?

**Comment by mvdan** [comment]
To clarify, this was when using Go-Package-Store, but I figured this is the place to open the issue.

**Comment by shurcooL** [comment]
> this was when using Go-Package-Store, but I figured this is the place to open the issue.

Thanks for the clarification, that's helpful.

Sure, I can consider this.

Ideally, I'd like to write as little code as possible for this task, and reuse as much as possible.

I believe I've seen `go bug` have some code that does this. I'll see if they implement support for `BROWSER` env var.

**Comment by shurcooL** [comment]
This is the code in GOROOT that does this:

https://github.com/golang/go/blob/ee4550440afd4f896dbcfe40c04e7fe11abd5a7b/src/cmd/internal/browser/browser.go#L41-L50

It appears they support the `BROWSER` env var:

```Go
if exe := os.Getenv("BROWSER"); exe != "" {
	cmds = append(cmds, []string{exe})
}
```

**Comment by mvdan** [comment]
Yup, but that's slightly different as you seem to do paths instead of just urls in your function.

**Comment by shurcooL** [comment]
Right, I'm aware of that. But luckily, I believe [all users](https://godoc.org/github.com/shurcooL/go/open?importers) of `open` only use it to open URLs, so I can safely reduce the scope. :)
